config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/index'

  root to: 'home#index'

  resources :users, only: [:create] do
    collection do
      get :logout
      post :login
    end
  end

  resources :courses, only: [:index, :new, :create, :show]
  resources :topics, only: [:new, :create, :destroy, :edit, :update]
  resources :learning_objectives, only: [:new, :create, :edit, :update, :destroy]
  resources :bloom_taxonomy_verbs
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
 def index;end
end

app/views/home/index.html.erb
<div class="jumbotron">
  <% if session[:user].present? %>
    <h1 class="display-4 text-center">Instructor Panel</h1>
  <% else %>
    <h1 class="display-4 text-center">Welcome to Instructor Portal!</h1>
  <% end %>
</div>

<div class='container-fluid'>
  <div class='row'>
    <div class="col-sm">
      <h2>Login Teacher</h2>
      <%= form_for :user, url: login_users_path, method: :post do |f| %>

        <div class="field form-group">
          <%= f.label :name %><br/>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <%= f.label :password %><br/>
          <%= f.password_field :password, class: 'form-control', required: true %>
        </div>

        <div class="actions">
          <%= f.submit "Login", class: 'btn btn-primary mb-2' %>
        </div>
      <% end %>
    </div>
    <div class="col-sm">
      <h2>Register Teacher</h2>
      <%= form_for :user, url: users_path, method: :post do |f| %>

        <div class="field form-group">
          <%= f.label :name %><br/>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <%= f.label :address %><br/>
          <%= f.text_field :address, class: 'form-control', required: true %>
        </div>

        <div class="field form-group">
          <%= f.label :phone_no %><br/>
          <%= f.text_field :phone_no, min: 3, class: 'form-control', required: true %>
        </div>
        <div>
          <p>Office Hours</p>
          <div class="field form-group">
            <%= f.time_field :office_hours_up, class: 'form-control', required: true %>
          </div>
          <div class="field form-group">
            <%= f.time_field :office_hours_to, class: 'form-control', required: true %>
          </div>
          <ul style="list-style: none; display: flex; gap: 10px; margin-left: -30px">
            <% Date::DAYNAMES.zip((0..6).to_a).each do |day| %>
              <li><%= check_box_tag 'days[]', day[0],[].include?(day[0]) -%>
              </li><%= day[0] -%>
            <% end %>
          </ul>
        </div>

        <div class="field form-group">
          <%= f.label :password %><br/>
          <%= f.password_field :password, class: 'form-control', required: true %>
        </div>

        <div class="actions">
          <%= f.submit "Register", class: 'btn btn-primary mb-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>