config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/index'

  root to: 'home#index'

  resources :users, only: [:create] do
    collection do
      get :logout
      post :login
    end
  end

  resources :courses, only: [:index, :new, :create, :show]
  resources :topics, only: [:new, :create, :destroy, :edit, :update]
  resources :learning_objectives, only: [:new, :create, :edit, :update, :destroy]
  resources :bloom_taxonomy_verbs
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :validate_session
  before_action :set_courses, only: [:index]

  def index
    respond_to do |format|
      format.html
    end
  end

  def new
    respond_to do |format|
      format.html
    end
  end

  def create
    course = Course.new(course_params)
    course.days = params[:days]
    if course.save
      flash[:success] = 'Course Successfully Created!'
      redirect_to courses_path
    else
      flash[:notice] = course.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
    # @Objective = LearningObjective.where(course_id: params[:id])
    @topics = @course.topics
    @blooms = BloomTaxonomyLevel.all
    @learning_objectives = LearningObjective.where(course_id: params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :code, :credit_hours, :user_id, :start_time, :end_time, :days, :location)
  end

  private

  def validate_session
    redirect_to root_path unless session[:user].present?
  end

  def set_courses
    @courses = Course.where(user_id: session.dig(:user, 'id'))
  end
end

app/views/courses/index.html.erb
<div class='container'>
  <br><br>
  <% row_count = 1 %>

  <div class='row'>
    <div class='col-sm mb-2'>
      <div class="card" style="width: 18rem; height: 100%; text-align: center;">
        <div class="card-header" style="height: 100%; padding-top: 15%">
          <h5 class="card-title"><a href="<%= new_course_path %>"><i class="fa fa-plus-circle"></i></a></h5>
        </div>
      </div>
    </div>
    <% @courses.includes(:user).each do |course| %>
      <div class='col-sm mb-2'>
        <div class="card" style="width: 18rem; text-align: center;">
          <div class="card-header">
            <h5 class="card-title"><%= link_to course.name, course_path(course.id) %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= course.code %></h6>
            <h6 class="card-subtitle mb-2 text-muted"><%= course.user.name %></h6>
            <h6 class="card-subtitle mb-2 text-muted"><%= "#{course.start_time.strftime("%I:%M%p")}" %></h6>
            <h6 class="card-subtitle mb-2 text-muted"><%= "#{course.end_time.strftime("%I:%M%p")}" %></h6>
            <h6 class="card-subtitle mb-2 text-muted"><%= course.credit_hours %></h6>
          </div>
        </div>
      </div>
      <% row_count += 1 %>
    <% end %>
    <% while row_count % 3 != 0 %>
      <div class='col-sm mb-2'></div>
      <% row_count += 1 %>
    <% end %>
  </div>


</div>

app/views/courses/new.html.erb
<div class='container-fluid'>
  <h2>Create Course</h2>
  <%= form_for :course, url: courses_path, method: :post do |f| %>

    <div class="field form-group">
      <%= f.label :name %><br/>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'form-control', required: true %>
    </div>

    <div class="field form-group">
      <%= f.label :code %><br/>
      <%= f.text_field :code, class: 'form-control', required: true %>
    </div>

    <div class="field form-group">
      <%= f.label :credit_hours %><br/>
      <%= f.number_field :credit_hours, min: 0, class: 'form-control', required: true %>
    </div>

    <div class="field form-group">
      <%= f.label :location %><br/>
      <%= f.text_field :location, class: 'form-control', required: true %>
    </div>

    <h6>Class Timing</h6>
    <div class="field form-group">
      <label>From</label><br/>
      <%= f.time_field :start_time, class: 'form-control', required: true %>
    </div>
    <div class="field form-group">
      <label>To</label><br/>
      <%= f.time_field :end_time, class: 'form-control', required: true %>
    </div>
    <ul style="list-style: none; display: flex; gap: 10px; margin-left: -30px">
      <% Date::DAYNAMES.zip((0..6).to_a).each do |day| %>
        <li><%= check_box_tag 'days[]', day[0], [].include?(day[0]) -%>
        </li><%= day[0] -%>
      <% end %>
    </ul>

    <div class="field form-group">
      <%= f.label 'Instructor' %><br/>
      <%= f.select :user_id, User.where(id: session.dig(:user, 'id')).map { |user| [user.name, user.id] }, {}, { class: ' form-control' } %>
    </div>

    <div class="actions">
      <%= link_to "Back", :back, class: 'btn btn-dark mb-2' %>
      <%= f.submit "Create", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-center"><%= @course.name %></h1>
  <h3 class="text-center"><%= @course.code %></h3>
</div>

<div class='container-fluid'>
  <%= link_to "Create Topic", new_topic_path(course_id: @course.id), class: 'btn btn-primary' %><br>
  <% unless @topics.any? == false %>
    <table class="table table-striped mt-2">
      <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Number of LO's mapped</th>
        <th colspan="2"></th>
      </tr>
      </thead>
      <tbody>
      <% @topics.each do |topic| %>
        <tr>
          <td><%= topic.description %></td>
          <% if topic.map_topics == [] || topic.map_topics.nil? %>
            <td style="color: red">no mapping for this topic</td>
          <% else %>
            <td><%= topic.map_topics&.join(', ') %></td>
          <% end %>
          <td style="text-align: right;">
            <%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-success' %>
            <%= link_to 'Delete', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<br><br>

<div class='container-fluid'>
  <%= link_to "Create Learning Objective", new_learning_objective_path(course_id: @course.id), class: 'btn btn-primary' %>
  <% unless @learning_objectives.any? == false %>
    <table class="table table-striped mt-2">
      <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Description</th>
        <th scope="col">Bloom’s taxonomy level</th>
        <th scope="col">Category</th>
        <th colspan="2"></th>
      </tr>
      </thead>
      <tbody>
      <% @learning_objectives.each_with_index do |learning_objective, index| %>
        <% indexplus = index + 1 %>
        <tr>
          <td>LO<%= indexplus %></td>
          <td><%= learning_objective.chosen_verb %> <%= learning_objective.description %></td>
          <td><%= learning_objective.bloom_taxonomy_level.level %></td>
          <td><%= learning_objective.category %></td>
          <td style="text-align: right">
            <%= link_to 'Edit', edit_learning_objective_path(learning_objective), class: 'btn btn-success' %>
            <%= link_to 'Delete', learning_objective, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>
<br/>
<div class='container-fluid'>
  <h2>Mappings</h2>
  <% unless @learning_objectives.any? == false %>
    <table class="table table-striped mt-2">
      <thead>
      <tr>
        <% @blooms.each do |bloom| %>
          <th scope="col"><%= bloom.level %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><%= @learning_objectives.remember.map { |t| "#{t.key}" }.join(", ") %></td>
        <td><%= @learning_objectives.understand.map { |t| "#{t.key}" }.join(", ") %></td>
        <td><%= @learning_objectives.apply.map { |t| "#{t.key}" }.join(", ") %></td>
        <td><%= @learning_objectives.analyze.map { |t| "#{t.key}" }.join(", ") %></td>
        <td><%= @learning_objectives.evaluate.map { |t| "#{t.key}" }.join(", ") %></td>
        <td><%= @learning_objectives.creat.map { |t| "#{t.key}" }.join(", ") %></td>
      </tr>
      </tbody>
    </table>
  <% end %>
</div>