config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home/index'

  root to: 'home#index'

  resources :users, only: [:create] do
    collection do
      get :logout
      post :login
    end
  end

  resources :courses, only: [:index, :new, :create, :show]
  resources :topics, only: [:new, :create, :destroy, :edit, :update]
  resources :learning_objectives, only: [:new, :create, :edit, :update, :destroy]
  resources :bloom_taxonomy_verbs
end

app/models/learning_objective.rb
class LearningObjective < ApplicationRecord
  enum category: %w[must important good]
  validates :description, presence: true, length: { minimum: 3 }
  validates :course_id, presence: true
  validates :bloom_taxonomy_level_id, presence: true
  validates :bloom_taxonomy_verb_id, presence: true
  validate :premium_category
  before_create :make_unique_key
  after_destroy :update_topic
  has_many :learning_objectives_topics
  has_many :topics, through: :learning_objectives_topics
  belongs_to :bloom_taxonomy_level
  belongs_to :course
  BLOOM_TAXONOMY_LEVEL = { 1 => 'Remember', 2 => 'Understand', 3 => 'Apply', 4 => 'Analyze', 5 => 'Evaluate', 6 => 'Create' }.freeze
  scope :remember, -> { where(bloom_taxonomy_level_id: 1) }
  scope :understand, -> { where(bloom_taxonomy_level_id: 2) }
  scope :apply, -> { where(bloom_taxonomy_level_id: 3) }
  scope :analyze, -> { where(bloom_taxonomy_level_id: 4) }
  scope :evaluate, -> { where(bloom_taxonomy_level_id: 5) }
  scope :creat, -> { where(bloom_taxonomy_level_id: 6) }

  # Temporary One because JS has to be added on BLOOM_TAXONOMY LEVEL CLICK
  BLOOM_TAXONOMY_VERB = { '1': [[1, 'Remember_1'], [2, 'Remember_2']], '2': [[3, 'Understand_1'], [4, 'Understand_2']] }.freeze

  VERIFICATION_KEYWORDS = %w[and or understand comprehend know].freeze

  def premium_category
    error = false
    VERIFICATION_KEYWORDS.each do |keyword|
      if self.description.downcase.split.include?(keyword)
        error = true
        errors.add(:base, "Error description cannot contain (#{keyword.upcase()}) LO is not saved!")
      end
    end
    if error
      throw :abort
    end
    true
  end

  def make_unique_key
    if LearningObjective.last.present?
      x = LearningObjective.last.id
    else
      x = "0".to_i
    end
    x = "LO" + "#{x + 1}"
    self.key = x
  end

  def update_topic
    Topic.all.map do |topic|
      if topic.map_topics&.include?(self.key)
        topic.map_topics.delete(self.key)
        if topic.map_topics.empty?
          topic.map_topics == []
        end
        topic.save
      end
    end
  end
end

app/controllers/learning_objectives_controller.rb
class LearningObjectivesController < ApplicationController
  before_action :validate_session
  before_action :set_bloom_taxonomy_levels, only: [:new, :edit]

  def new
    @course_id = params[:course_id]
    @course = Course.find(@course_id)
    @topics = @course.topics
    respond_to do |format|
      format.html
    end
  end

  def edit
    @learning_object = LearningObjective.find(params[:id])
    @course_id = @learning_object.course_id
  end

  def create
    course = Course.find(learning_objective_params[:course_id])
    topic_ids = []
    new_params = learning_objective_params
    params[:learning_objective].keys.each do |key|
      topic_ids = topic_ids << key.split('_').last if key.include?('topic_') && params[:learning_objective][key] == '1'
    end
    learning_objective = LearningObjective.new(new_params)
    if course.present? && learning_objective.save
      # binding.pry
      params[:topic]&.each do |d|
        topic = Topic.find_by_id(d)
        if topic["map_topics"].nil?
          topic["map_topics"] = learning_objective.key
        end
        @map_topic = topic["map_topics"] << learning_objective.key
        topic.update("map_topics" => @map_topic)
      end
      topic_ids.each do |topic_id|
        LearningObjectiveTopic.create(topic_id: topic_id, learning_objective_id: learning_objective.id)
      end
      flash[:success] = 'Learning Objective Successfully Created!'
      redirect_to course_path(course.id)
    else
      flash[:notice] = learning_objective.errors.full_messages.join("; ")
      redirect_to course_path(course.id)
    end
  end

  def destroy
    @learning_object = LearningObjective.find_by_id(params[:id])
    if @learning_object.present?
      @course = @learning_object.course
      @learning_object.destroy
    end
    flash[:success] = 'Learning objective successfully delete!'
    redirect_to @course
  end

  def update
    topic_ids = []
    params[:learning_objective].keys.each do |key|
      topic_ids = topic_ids << key.split('_').last if key.include?('topic_') && params[:learning_objective][key] == '1'
    end
    @learning_objective = LearningObjective.find(params[:id])
    course = Course.find(@learning_objective.course_id)
    if @learning_objective.update(update_params)
      if params[:topic].nil?
        Topic.all.map do |topic|
          if topic.map_topics&.include?(@learning_objective.key)
            topic.map_topics.delete(@learning_objective.key)
            if topic.map_topics.empty?
              topic.map_topics == []
            end
            topic.save
          end
        end
      end
      params[:topic]&.each do |d|
        topic = Topic.find_by_id(d)
        if topic["map_topics"].nil?
          topic["map_topics"] = @learning_objective.key
        end
        @map_topic = topic["map_topics"] << @learning_objective.key
        topic.update("map_topics" => @map_topic.uniq)
      end
      topic_ids.each do |topic_id|
        LearningObjectiveTopic.create(topic_id: topic_id, learning_objective_id: @learning_objective.id)
      end
      flash[:success] = 'Learning objective successfully updated!'
      redirect_to course
    else
      flash[:notice] = @learning_objective.errors.full_messages.join("; ")
      redirect_to course
    end
  end

  def learning_objective_params
    params.require(:learning_objective).permit(:description, :bloom_taxonomy_level_id, :bloom_taxonomy_verb_id, :course_id, :key, :category, :chosen_verb)
  end

  def validate_session
    redirect_to root_path unless session[:user].present?
  end

  def update_params
    params.require(:learning_objective).permit(:description, :bloom_taxonomy_level_id, :bloom_taxonomy_verb_id, :course_id, :key, :category, :chosen_verb)
  end

  def set_bloom_taxonomy_levels
    @bloom_taxonomy_levels = BloomTaxonomyLevel.all
  end

end


app/views/learning_objectives/create_learning_objective.html.erb
<div class='container-fluid'>
  <h3>Step 3: Let's finish writing up the learning objective!</h3> <br/>

  <h6>You chose the verb "<%= @bloom_taxonomy_verb_name %>". Now write what you want students
    to <%= @bloom_taxonomy_verb_name %>.<br/><br/>
    When writing your learning objective, remember:<br/><br/>
    <ul>
      <li class='italic'>Learning objective must be specific</li>
      <li class='italic'>Do not combine two objectives into one</li>
      <li class='italic'>Do not use understand, know, or comprehend in your learning objective</li>
    </ul>
  </h6>
  <%= form_for :learning_objective, url: learning_objectives_path, method: :post do |f| %>
    <div class="field form-group flex">

      <%= f.text_field :chosen_verb, value: @bloom_taxonomy_verb_name, class: 'form-control verb', required: true, readonly: true %>
      <%= f.text_field :description, autofocus: true, placeholder: "write learning objective...", class: 'form-control description', required: true %>
      <%= f.label :chosen_verb, class: 'verb' %>
      <%= f.label :description, class: 'description' %>
      <%= f.label :category %>
      <%= f.select :category, options_for_select(LearningObjective.categories.keys.map { |key| [key.titlecase, key] }), {}, { class: "form-control" } %>
    </div>

    <h3>Step 4: Map the learning objective to course topics (Optional)</h3><br/>
    <div class="field form-group">
      <%= f.label 'Select topics to map' %><br/><br/>
      <div class="flex">
        <% @topics&.each do |topic| %>
          <div class="field">
            <%= check_box_tag 'topic[]', topic.id %>
            <%= f.label topic.description %>
            <br/>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.hidden_field :course_id, value: @course_id %>
    <%= f.hidden_field :bloom_taxonomy_level_id, value: @bloom_taxonomy_level_id %>
    <%= f.hidden_field :bloom_taxonomy_verb_id, value: @bloom_taxonomy_verb_id %>

    <div class="actions">
      <%= link_to "Back", :back, class: 'btn btn-outline-dark mb-2' %>
      <%= f.submit "Create", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>
</div>

app/views/learning_objectives/edit.html.erb
<%= stylesheet_link_tag "taxonomy" %>
<div class='container-fluid'>
  <h3 class="header">Edit your Learning Objective!</h3>
  <h6>We'll be creating learning objectives based on Bloom's taxonomy. Bloom’s taxonomy provides a systematic
    classification of the learning and thinking process.
    It classifies knowledge into 6 levels that increase in complexity: remember, understand, apply, analyze, evaluate,
    create. Refer to the table below for the overview of each knowledge level.
  </h6>
  <%= image_tag("bloomlevels.png", class: 'taxonomy_img') %>

  <h5>Now let's edit your Bloom's Taxonomy Level</h5>
  <%= form_for :bloom_taxonomy_verb, url: :edit_bloom_taxonomy_verb, method: :get do |f| %>
    <div class="field form-group">
      <%= f.label :bloom_taxonomy_level_id %><br/>
      <%= f.select :bloom_taxonomy_level_id, (@bloom_taxonomy_levels || []).map { |objective| [objective.level, objective.id] }, {}, { class: ' form-control' } %>
    </div>
    <%= f.hidden_field :course_id, value: @course_id %>
    <div class="actions">
      <%= f.submit "Next", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>
</div>

app/views/learning_objectives/new.html.erb
<%= stylesheet_link_tag "taxonomy" %>
<div class='container-fluid'>
  <h3 class="header">Welcome to the Learning Objectives Builder!</h3>
  <h6>We'll be creating learning objectives based on Bloom's taxonomy. Bloom’s taxonomy provides a systematic
    classification of the learning and thinking process.
    It classifies knowledge into 6 levels that increase in complexity: remember, understand, apply, analyze, evaluate,
    create. Refer to the table below for the overview of each knowledge level.
  </h6>
  <%= image_tag("bloomlevels.png", class: 'taxonomy_img') %>

  <h5>Now let's select your Bloom's Taxonomy Level</h5>
  <%= form_for :bloom_taxonomy_verb, url: new_bloom_taxonomy_verb_path, method: :get do |f| %>

    <div class="field form-group">
      <%= f.label :bloom_taxonomy_level_id %><br/>
      <%= f.select :bloom_taxonomy_level_id, (@bloom_taxonomy_levels || []).map { |objective| [objective.level, objective.id] }, {}, { class: ' form-control' } %>
    </div>

    <%= f.hidden_field :course_id, value: @course_id %>

    <div class="actions">
      <%= f.submit "Next", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>
</div>

app/views/learning_objectives/update_learning_objective.html.erb
<div class='container-fluid'>
  <h3>Step 3: Let's finish writing up the learning objective!</h3> <br/>

  <h6>You chose the verb "<%= @bloom_taxonomy_verb_name %>". Now write what you want students
    to <%= @bloom_taxonomy_verb_name %>.<br/><br/>
    When writing your learning objective, remember:<br/><br/>
    <ul>
      <li class='italic'>Learning objective must be specific</li>
      <li class='italic'>Do not combine two objectives into one</li>
      <li class='italic'>Do not use understand, know, or comprehend in your learning objective</li>
    </ul>
  </h6>
  <%= form_for :learning_objective, url: :learning_objective, method: :patch do |f| %>
    <div class="field form-group flex">
      <%= f.text_field :chosen_verb, value: @bloom_taxonomy_verb_name, class: 'form-control verb', required: true, readonly: true %>
      <%= f.text_field :description, autofocus: true, placeholder: "write learning objective...", class: 'form-control description', required: true %>
      <%= f.label :chosen_verb, class: 'verb' %>
      <%= f.label :description, class: 'description' %>
      <%= f.label :category %>
      <%= f.select :category, options_for_select(LearningObjective.categories.keys.map { |key| [key.titlecase, key] }), {}, { class: "form-control" } %>
    </div>

    <h3>Step 4: Map the learning objective to course topics (Optional)</h3><br/>
    <div class="field form-group">
      <%= f.label 'Select topics to map' %><br/><br/>
      <div class="flex">
        <% @topics&.each do |topic| %>
          <div class="field">
            <%= check_box_tag 'topic[]', topic.id %>
            <%= f.label topic.description %>
            <br/>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.hidden_field :course_id, value: @course_id %>
    <%= f.hidden_field :bloom_taxonomy_level_id, value: @bloom_taxonomy_level_id %>
    <%= f.hidden_field :bloom_taxonomy_verb_id, value: @bloom_taxonomy_verb_id %>

    <div class="actions">
      <%= link_to "Back", :back, class: 'btn btn-outline-dark mb-2' %>
      <%= f.submit "Update", class: 'btn btn-primary mb-2' %>
    </div>
  <% end %>
</div>